pipeline {
    // Mandatory to use per-stage agents
    agent none
    stages {
        stage('Build - test') {
            agent {
                docker {
                    image 'node:9-alpine'
                    // TODO some cache to avoid npm sintall on every execution?
                }
            }
            steps {
				// cr src > if the code is in src folder
                sh 'cd src; npm install'

                // Run the tests?
                // TO-DO
            }
            // TODO stop if test fails!
            post {
                always {
                    // Record the test report?
                    // TO-DO
            echo "TO-DO Record tests"
                }
            }
        }
        stage('Image creation') {
            agent any
            steps {
                // The Dockerfile.artifact copies the code into the image and run the jar generation.
                echo 'Creating the image...'
                // This will search for a Dockerfile.artifact in the working directory and build the image to the local repository
                sh "docker build -t \"ditas/IMAGE_NAME\" -f Dockerfile.artifact ."
                echo "Done"
                echo 'Retrieving Docker Hub password from /opt/ditas-docker-hub.passwd...'
                // Get the password from a file. This reads the file from the host, not the container. Slaves already have the password in there.
                script {
                    password = readFile '/opt/ditas-docker-hub.passwd'
                }
                echo "Done"
                echo 'Login to Docker Hub as ditasgeneric...'
                sh "docker login -u ditasgeneric -p ${password}"
                echo "Done"
                echo "Pushing the image ditas/IMAGE_NAME:latest..."
                sh "docker push ditas/IMAGE_NAME:latest"
                echo "Done "
            }
        }
        stage('Image deploy') {
            // TO-DO avoid downloading the source from git again, not neccessary
            agent any
            steps {
                // Staging environment: 31.171.247.162
                // Private key for ssh: /opt/keypairs/ditas-testbed-keypair.pem

                // TODO state management? We are killing without careing about any operation the conainer could be doing.

                // Ensure that a previously running instance is stopped (-f stops and removes in a single step)
                // || true - "docker stop" failt with exit status 1 if image doen't exists, what makes the Pipeline fail. the "|| true" forces the command to exit with 0.
                sh 'ssh -i /opt/keypairs/ditas-testbed-keypair.pem cloudsigma@31.171.247.162 sudo docker rm -f IMAGE_NAME || true'

                // Ensure that the last image is pulled
                sh 'ssh -i /opt/keypairs/ditas-testbed-keypair.pem cloudsigma@31.171.247.162 sudo docker pull ditas/IMAGE_NAME:latest'

                // Run and name the image to allow stopping by name
                // TODO tune the run command
                sh 'ssh -i /opt/keypairs/ditas-testbed-keypair.pem cloudsigma@31.171.247.162 sudo docker run -p 50000:8080 -d --name IMAGE_NAME ditas/IMAGE_NAME:latest'
            }
        }
    }
}
